### ISSUE TITLE
A non-numeric value encountered in number.inc

### ISSUE THREAD

**Issue by PROMES** [d6lts/webform#1]
After updating to 6.x-3.26 I got this message whenever a webpage is visited:
A non-numeric value encountered in xxx/sites/all/modules/webform/components/number.inc on line 309.
My solution: line 309 from:
`  if !is_int($element['#step'] * 1)) {`
into:
`  if (!empty($element['#step']) && !is_int($element['#step'] * 1)) {`

**Comment by dsnopek** [comment]
Thanks! Added a commit that should fix this
